### ISSUE TITLE
Combining --s3-upload-prefix with --region parameter does not work

### ISSUE THREAD

**Issue by grddev** [burtcorp/cuffsert#21]
When computing the location parameter for the template URL, the region parameter isn't used (and you get an error with a URL like:

```
https://s3-eu-west-1.amazonaws.com/cf-templates-account-us-east-1/some/template/prefix/file.json
```

Where you can note the difference in region in the hostname and path. I suppose the "best" solution would be to infer the region of the bucket from the bucket itself, but it would seem reasonable to at least use the region parameter as the default.

You can workaround the issue by passing the region through environment variables instead.

**Comment by bittrance** [comment]
Thanks for reporting this. Yes, the code needs to find the region (i.e. construct an HTTPS URL from a bucket name) since CloudFormation does not accept an S3 URL 😒 :
```
$ aws cloudformation create-change-set --stack-name some-stack --template-url s3://cf-templates-account-eu-west-1/some-stack.json --change-set-name test
An error occurred (ValidationError) when calling the CreateChangeSet operation: The specified url must be an Amazon S3 URL.

$ aws cloudformation create-change-set --stack-name some-stack --template-url https://s3-eu-west-1.amazonaws.com/cf-templates-account-eu-west-1/some-stack.json --change-set-name test
{
    "Id": "arn:aws:cloudformation:eu-west-1:account:changeSet/test/uuid",
    "StackId": "arn:aws:cloudformation:eu-west-1:account:stack/some-stack/uuid"
}
```
This means that you can use one global bucket, so we would indeed need to do `GetBucketLocation`. Of course, that means we need to handle the idiosyncrasies of `LocationConstraint`. Just assuming the bucket is in the same region is a good start.
